import os

TIEMPO_MAXIMO_BUSQUEDA_PARTIDA = 10
CLAVE_CIFRADO = "and2502jdakdwajadjdakodaokd121jdqdok1202412ijo41ndkdajdjdeurnvjvnkadnkdas" + \
                "dakjdkjadjkadakjda21djqwqjqd2204ajdj21dakjdakjdakjdda"
TAMANO_CHUNK = 124
BYTES_LARGO = 4
ID_BYTES = 4
PAQUETES_LARGO = 128
MINIMO_PALABRAS_CONJUNTO = 10
VIDAS_INICIALES = 3
DIFICULTAD_BASE = 1
INCREMENTO_DIFICULTAD = 1
TIEMPO_INCREMENTO_DIFICULTAD = 1
TIEMPO_APARICION_MAXIMO = 3
TIEMPO_APARICION_MINIMO = 1
TIEMPO_CAIDA_MAXIMO = 300
PROBABILIDAD_BLOQUE_HIELO = 0.5
TIEMPO_CONGELACION_BLOQUE_HIELO = 1
LARGO_MINIMO_BLOQUE_BRUMA = 4
PROBABILIDAD_BLOQUE_BRUMA = 0.5
TIEMPO_BLOQUEO_BRUMA = 1
PATH_CONEXION_BACKEND = os.path.join("backend", "conexion.json")

